### ISSUE TITLE
Add jdk to the scanned images

### ISSUE THREAD

**Issue by bennetelli** [chainguard-dev/image-comparison#37]
Hi there,

it would be great if you could add the chainguard jdk images to this table: https://github.com/chainguard-dev/image-comparison/blob/main/data.csv

Thanks in advance :)

**Comment by jspeed-meyers** [comment]
@bennetelli, making the jdk data available here (or another public location) is on the short-term (next quarter) plan. So yes!

Caveat: The jdk images are wolfi-based, and neither `trivy` nor `grype` is yet fully compatible with wolfi-based images. But that should change soon, especially for `trivy`: `trivy`'s next release will include wolfi compatibility. So that should unblock making this data publicly available :)

Will keep you informed!

**Comment by bennetelli** [comment]
yea, that would be great so people can compare your great work with other base images :)

**Comment by jspeed-meyers** [comment]
`trivy` and `grype` are now compatible with wolfi-based images. Next step: determining the best way to release this data regularly.

**Comment by jdolitsky** [comment]
closing for now, but feel free to re-open if necessary
